# Site settings
title: Sean Arnold
tagline: Front End Developer
email: tandysean@gmail.com
description: > # this means to ignore newlines until "baseurl:"Í
baseurl: "/build" # the subpath of your site, e.g. /blog/
url: "tandysean.github.io" # the base hostname & protocol for your site
twitter_username: tandysean
github_username:  tandysean



# Build settings
markdown: kramdown

source: ./app
destination: ./build
